version: '3.3'
services:
    postgis:
        image: postgis/postgis:13-3.0-alpine
        environment:
          - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
          - POSTGRES_USER=$POSTGRES_USER
          - POSTGRES_DB=$POSTGRES_DB
          - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
          - './pg-data:/var/lib/postgresql/data'
        ports:
          - $POSTGRES_PORT:5432
        restart: unless-stopped
    
