wipe-db:
  image:
    name: flyway/flyway:latest
    entrypoint: [""]
  variables:
    host: $dbdevmachine1ip
    port: 3010
    database: bmgf
    schemas: bmgf
    user: $devdb1_user
    password: $devdeb1_password
  script:
    - echo $host
    - flyway clean   -url="jdbc:postgresql://${host}:${port}/${database}" -user=${user} -password=${password} -schemas=${schemas}
    - flyway migrate -url="jdbc:postgresql://${host}:${port}/${database}" -user=${user} -password=${password} -schemas=${schemas} -locations=filesystem:db/,filesystem:raw-data -validateOnMigrate=true
    - flyway info    -url="jdbc:postgresql://${host}:${port}/${database}" -user=${user} -password=${password} -schemas=${schemas} -locations=filesystem:db/,filesystem:raw-data

